CREATE DATABASE FoodCarnival;
USE FoodCarnival;

CREATE TABLE COMMERCE(
	CommerceID INT NOT NULL,
    Pass VARCHAR (30) NOT NULL,
    CommerceName VARCHAR (30) NOT NULL,
    CommerceDescription TINYTEXT NULL,
    Suburb VARCHAR (30) NOT NULL,
    Street VARCHAR (30) NOT NULL,
    OutdoorNum VARCHAR(10) NOT NULL,
    MaxRequisitionNum TINYINT NOT NULL
);

CREATE TABLE CUSTOMER(
	CustomerID INT NOT NULL,
    UserName VARCHAR (20) NOT NULL,
    Pass VARCHAR (20) NOT NULL,
    CustomerName VARCHAR (20) NOT NULL,
    LastName VARCHAR (20) NOT NULL,
    Email VARCHAR (30) NOT NULL
);

CREATE TABLE SAUCER(
	SaucerID INT NOT NULL,
    SaucerName VARCHAR (20) NOT NULL,
    SaucerDes TINYTEXT NULL,
    CookingTime TINYINT NOT NULL,
    CommerceID INT NOT NULL
);

CREATE TABLE PAY_METHODS(
	CustomerID INT NOT NULL,
    Method ENUM('PayPal', 'Efectivo')
);

/*Primary Keys*/
ALTER TABLE COMMERCE
ADD CONSTRAINT COMMERCE_PK PRIMARY KEY (CommerceID);

ALTER TABLE CUSTOMER
ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY (CustomerID);

ALTER TABLE SAUCER
ADD CONSTRAINT SAUCER_PK PRIMARY KEY (SaucerID);

/*Foreing Keys*/
ALTER TABLE SAUCER
ADD CONSTRAINT SAUCER_COMMERCE_FK FOREIGN KEY (CommerceID) REFERENCES COMMERCE(CommerceID);

ALTER TABLE PAY_METHODS
ADD CONSTRAINT PMETHOD_CUSTOMER_FK FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID);


/*DEFAULT*/
ALTER TABLE COMMERCE
ALTER Pass SET DEFAULT '1234';